"""
Database seeder script for Shark Recovery.
Populates SQLite with realistic Indian SaaS & E-commerce payment failure and recovery records.
"""

import asyncio
import json
import random
import uuid
from datetime import datetime, timedelta
from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select, delete

try:
    from backend.database import async_session_maker, init_db
    from backend.models.audit_log import ActionType, AuditLog, AuditStatus
    from backend.models.customer import Customer
    from backend.models.schemas import (
        DiagnosticContext,
        EmailPayload,
        RazorpayPaymentLinkCreate,
        RecoveryChannel,
        WhatsAppPayload,
    )
    from backend.models.transaction import (
        FailureCategory,
        LossVector,
        Transaction,
        TransactionStatus,
    )
except ImportError:
    from database import async_session_maker, init_db
    from models.audit_log import ActionType, AuditLog, AuditStatus
    from models.customer import Customer
    from models.schemas import (
        DiagnosticContext,
        EmailPayload,
        RazorpayPaymentLinkCreate,
        RecoveryChannel,
        WhatsAppPayload,
    )
    from models.transaction import (
        FailureCategory,
        LossVector,
        Transaction,
        TransactionStatus,
    )

SEED_CUSTOMERS = [
    {
        "name": "Pooja Hegde",
        "email": "pooja.hegde@techflow.in",
        "phone": "+919820123456",
        "total_spent": 14200.0,
        "txns": 5,
        "failed_txns": 1,
        "amount": 3499.0,
        "code": "BAD_REQUEST_ERROR",
        "reason": "Payment failed due to daily UPI debit limit exceeded",
        "category": FailureCategory.INSUFFICIENT_FUNDS,
        "loss_vector": LossVector.CHECKOUT_DROPOFF,
        "status": TransactionStatus.RECOVERED,
        "escalation_level": 1,
        "discount": 10.0,
        "channel": "whatsapp",
        "recovered": 3149.10,
        "retries": 1,
        "minutes_ago": 25,
        "customer_intent": "DISCOUNT_ACCEPTED",
        "root_cause_discovery": "Daily UPI limit reached on secondary bank account; customer switched to HDFC UPI handle and completed checkout",
        "promise_to_pay_date": None,
        "ptp_status": None,
        "voice_transcript": None,
    },
    {
        "name": "Rohan Verma",
        "email": "rohan.verma@quickpay.co",
        "phone": "+919811987654",
        "total_spent": 8500.0,
        "txns": 3,
        "failed_txns": 1,
        "amount": 1899.0,
        "code": "AUTHENTICATION_TIMEOUT",
        "reason": "OTP verification timed out on HDFC netbanking portal after 180s",
        "category": FailureCategory.AUTHENTICATION_FAILED,
        "loss_vector": LossVector.CHECKOUT_DROPOFF,
        "status": TransactionStatus.RECOVERED,
        "escalation_level": 1,
        "discount": 5.0,
        "channel": "whatsapp",
        "recovered": 1804.05,
        "retries": 1,
        "minutes_ago": 45,
        "customer_intent": "DISCOUNT_ACCEPTED",
        "root_cause_discovery": "SMS OTP delayed due to local telecom congestion; recovered instantly via WhatsApp 1-click Razorpay payment link",
        "promise_to_pay_date": None,
        "ptp_status": None,
        "voice_transcript": None,
    },
    {
        "name": "Deepak Gupta",
        "email": "deepak.gupta@enterprise.io",
        "phone": "+919711002233",
        "total_spent": 24900.0,
        "txns": 8,
        "failed_txns": 1,
        "amount": 5499.0,
        "code": "GATEWAY_ERROR",
        "reason": "SBI gateway server 503 temporary CBS outage during 3DS redirect",
        "category": FailureCategory.BANK_SERVER_ERROR,
        "loss_vector": LossVector.GATEWAY_SPIKE,
        "status": TransactionStatus.RECOVERED,
        "escalation_level": 2,
        "discount": 0.0,
        "channel": "email",
        "recovered": 5499.00,
        "retries": 1,
        "minutes_ago": 60,
        "customer_intent": "TECHNICAL_OBJECTION",
        "root_cause_discovery": "SBI CBS network maintenance window; zero churn intent, retried and recovered automatically once SBI gateway stabilized",
        "promise_to_pay_date": None,
        "ptp_status": None,
        "voice_transcript": None,
    },
    {
        "name": "Vikramaditya Roy",
        "email": "vikram.roy@execstrategy.in",
        "phone": "+919830012345",
        "total_spent": 38000.0,
        "txns": 4,
        "failed_txns": 1,
        "amount": 18500.0,
        "code": "INSUFFICIENT_FUNDS",
        "reason": "Daily debit ceiling breached on ICICI corporate salary account",
        "category": FailureCategory.INSUFFICIENT_FUNDS,
        "loss_vector": LossVector.VOICE_RECOVERY,
        "status": TransactionStatus.PROCESSING,
        "escalation_level": 5,
        "discount": 10.0,
        "channel": "voice_ivr",
        "recovered": 0.0,
        "retries": 1,
        "minutes_ago": 15,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "Customer agreed to complete enrollment tomorrow morning once salary credit of ₹1,85,000 clears in ICICI account",
        "promise_to_pay_date": "Tomorrow 11:30 AM",
        "ptp_status": "PENDING",
        "voice_transcript": {
            "call_id": "call_vroy_9830",
            "customer_name": "Vikramaditya Roy",
            "customer_phone": "+919830012345",
            "customer_email": "vikram.roy@execstrategy.in",
            "order_amount": 18500.0,
            "discount_offered": 10.0,
            "customer_intent": "PROMISE_TO_PAY",
            "root_cause_discovery": "Customer agreed to complete enrollment tomorrow morning once salary credit of ₹1,85,000 clears in ICICI account",
            "promise_to_pay_date": "Tomorrow 11:30 AM",
            "call_outcome": "PROMISED",
            "call_duration_seconds": 88,
            "sms_payment_link_triggered": True,
            "failure_reason": "Daily debit ceiling breached on ICICI corporate salary account",
            "dialogue": [
                {"speaker": "agent", "text": "Namaste Vikramaditya ji, Priya calling from Shark Executive Learning. I noticed your registration for the Leadership Track couldn't go through due to a bank limit."},
                {"speaker": "customer", "text": "Haan Priya, actually mera ICICI corporate account ka daily limit exhaust ho gaya tha because of another vendor payment today."},
                {"speaker": "agent", "text": "Bilkul samajh sakti hoon Vikramaditya ji. We have reserved your seat and unlocked a special 10% privilege discount (INR 1,850 savings). Kab tak comfortable rahega payment complete karna?"},
                {"speaker": "customer", "text": "Tomorrow morning by 11:30 AM salary credit ho jayegi, I will definitely complete it then."},
                {"speaker": "agent", "text": "Perfect! Main kal subah 11:30 AM ka promise-to-pay lock kar rahi hoon aur direct payment link aapke WhatsApp pe bhej diya hai. Thank you so much!"}
            ]
        },
    },
    {
        "name": "Sneha Reddy",
        "email": "sneha.reddy@gmail.com",
        "phone": "+919886098765",
        "total_spent": 12000.0,
        "txns": 2,
        "failed_txns": 1,
        "amount": 8999.0,
        "code": "INSUFFICIENT_FUNDS",
        "reason": "Insufficient balance in Kotak savings account for annual subscription",
        "category": FailureCategory.INSUFFICIENT_FUNDS,
        "loss_vector": LossVector.VOICE_RECOVERY,
        "status": TransactionStatus.PROCESSING,
        "escalation_level": 4,
        "discount": 15.0,
        "channel": "voice_ivr",
        "recovered": 0.0,
        "retries": 1,
        "minutes_ago": 35,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "Customer requested payment link deferred to salary cycle on 1st of next month; 15% annual incentive accepted",
        "promise_to_pay_date": "Payday: 1st of Month",
        "ptp_status": "PENDING",
        "voice_transcript": {
            "call_id": "call_sred_9886",
            "customer_name": "Sneha Reddy",
            "customer_phone": "+919886098765",
            "customer_email": "sneha.reddy@gmail.com",
            "order_amount": 8999.0,
            "discount_offered": 15.0,
            "customer_intent": "PROMISE_TO_PAY",
            "root_cause_discovery": "Customer requested payment link deferred to salary cycle on 1st of next month; 15% annual incentive accepted",
            "promise_to_pay_date": "Payday: 1st of Month",
            "call_outcome": "PROMISED",
            "call_duration_seconds": 72,
            "sms_payment_link_triggered": True,
            "failure_reason": "Insufficient balance in Kotak savings account",
            "dialogue": [
                {"speaker": "agent", "text": "Hello Sneha ji! Priya here from EdTech Pro. Aapka annual plan checkout complete nahi ho paya tha."},
                {"speaker": "customer", "text": "Priya actually iss month ka balance low hai. Salary 1st ko aayegi tabhi kar paungi."},
                {"speaker": "agent", "text": "Arrey bilkul koi baat nahi! Humne aapke liye 15% discount hold kiya hai aur reminder 1st ko schedule kar diya hai."},
                {"speaker": "customer", "text": "That's great! 1st ko subah link bhej dijiyega, main card se pay kar dungi."},
                {"speaker": "agent", "text": "Done Sneha ji! Schedule lock ho gaya hai. Have a wonderful day!"}
            ]
        },
    },
    {
        "name": "Kavita Nair",
        "email": "kavita.nair@cloudpulse.tech",
        "phone": "+919840112233",
        "total_spent": 52000.0,
        "txns": 6,
        "failed_txns": 1,
        "amount": 24500.0,
        "code": "PAYMENT_DECLINED",
        "reason": "Corporate credit card online transaction limits toggled off in Axis Netbanking",
        "category": FailureCategory.PAYMENT_DECLINED,
        "loss_vector": LossVector.B2B_RECEIVABLE,
        "status": TransactionStatus.PROCESSING,
        "escalation_level": 3,
        "discount": 5.0,
        "channel": "voice_ivr",
        "recovered": 0.0,
        "retries": 1,
        "minutes_ago": 50,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "CFO authorization required to enable online card mandate; promised payment today by 6:00 PM",
        "promise_to_pay_date": "Today by 6:00 PM",
        "ptp_status": "PENDING",
        "voice_transcript": {
            "call_id": "call_knair_9840",
            "customer_name": "Kavita Nair",
            "customer_phone": "+919840112233",
            "customer_email": "kavita.nair@cloudpulse.tech",
            "order_amount": 24500.0,
            "discount_offered": 5.0,
            "customer_intent": "PROMISE_TO_PAY",
            "root_cause_discovery": "CFO authorization required to enable online card mandate; promised payment today by 6:00 PM",
            "promise_to_pay_date": "Today by 6:00 PM",
            "call_outcome": "PROMISED",
            "call_duration_seconds": 65,
            "sms_payment_link_triggered": True,
            "failure_reason": "Corporate credit card online transaction limits toggled off in Axis Netbanking",
            "dialogue": [
                {"speaker": "agent", "text": "Good afternoon Kavita ji. AI Shark recovery desk calling regarding CloudPulse cloud retainer invoice."},
                {"speaker": "customer", "text": "Hi Priya, hamare corporate card pe e-comm limit off thi. Maine CFO ko approval raise kar diya hai."},
                {"speaker": "agent", "text": "Understood Kavita ji. Approximate kis time tak approval expect kar sakte hain?"},
                {"speaker": "customer", "text": "Today by 6:00 PM pakka ho jayega."},
                {"speaker": "agent", "text": "Excellent! I have recorded your commitment for 6 PM today and sent the direct invoice link."}
            ]
        },
    },
    {
        "name": "Aditya Verma",
        "email": "aditya.v@luxetime.in",
        "phone": "+919871098712",
        "total_spent": 45000.0,
        "txns": 3,
        "failed_txns": 1,
        "amount": 38500.0,
        "code": "AUTHENTICATION_TIMEOUT",
        "reason": "Customer in flight during checkout; SIM dropped signal during 3DS challenge",
        "category": FailureCategory.AUTHENTICATION_FAILED,
        "loss_vector": LossVector.VOICE_RECOVERY,
        "status": TransactionStatus.RECOVERED,
        "escalation_level": 3,
        "discount": 5.0,
        "channel": "voice_ivr",
        "recovered": 36575.00,
        "retries": 1,
        "minutes_ago": 180,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "Customer requested payment link sent via WhatsApp for evening after flight landed; commitment fulfilled smoothly",
        "promise_to_pay_date": "Yesterday 8:00 PM",
        "ptp_status": "FULFILLED",
        "voice_transcript": {
            "call_id": "call_averm_9871",
            "customer_name": "Aditya Verma",
            "customer_phone": "+919871098712",
            "customer_email": "aditya.v@luxetime.in",
            "order_amount": 38500.0,
            "discount_offered": 5.0,
            "customer_intent": "PROMISE_TO_PAY",
            "root_cause_discovery": "Customer requested payment link sent via WhatsApp for evening after flight landed; commitment fulfilled smoothly",
            "promise_to_pay_date": "Yesterday 8:00 PM",
            "call_outcome": "FULFILLED",
            "call_duration_seconds": 95,
            "sms_payment_link_triggered": True,
            "failure_reason": "Customer in flight during checkout; SIM dropped signal during 3DS challenge",
            "dialogue": [
                {"speaker": "agent", "text": "Namaste Aditya ji! Priya from LuxeTime concierge. Your timepiece order got interrupted during payment verification."},
                {"speaker": "customer", "text": "Haan Priya, I was boarding a flight at Delhi airport and network disconnect ho gaya tha."},
                {"speaker": "agent", "text": "No worries Aditya ji! Your limited-edition piece is reserved. Can I schedule a WhatsApp link for when you land?"},
                {"speaker": "customer", "text": "Yes please, send it for 8 PM tonight. I will pay via UPI right after landing."},
                {"speaker": "agent", "text": "Superb! Scheduled for 8 PM. Safe flight!"}
            ]
        },
    },
    {
        "name": "Tanvi Deshmukh",
        "email": "tanvi.deshmukh@wellnesskart.com",
        "phone": "+919822334455",
        "total_spent": 5800.0,
        "txns": 1,
        "failed_txns": 2,
        "amount": 6499.0,
        "code": "USER_DROPOUT",
        "reason": "Customer closed browser checkout tab during payment processing",
        "category": FailureCategory.USER_DROPOUT,
        "loss_vector": LossVector.CHECKOUT_DROPOFF,
        "status": TransactionStatus.FAILED,
        "escalation_level": 2,
        "discount": 10.0,
        "channel": "whatsapp",
        "recovered": 0.0,
        "retries": 2,
        "minutes_ago": 240,
        "customer_intent": "TECHNICAL_OBJECTION",
        "root_cause_discovery": "Customer found local clinic alternative; commitment window passed without recovery",
        "promise_to_pay_date": "Expired 2 days ago",
        "ptp_status": "BREACHED",
        "voice_transcript": None,
    },
    {
        "name": "Siddharth Joshi",
        "email": "siddharth.j@devforge.io",
        "phone": "+919766554433",
        "total_spent": 31000.0,
        "txns": 5,
        "failed_txns": 1,
        "amount": 12000.0,
        "code": "GATEWAY_ERROR",
        "reason": "Axis Bank 3D Secure ACS authentication server unresponsive",
        "category": FailureCategory.BANK_SERVER_ERROR,
        "loss_vector": LossVector.GATEWAY_SPIKE,
        "status": TransactionStatus.RECOVERED,
        "escalation_level": 1,
        "discount": 0.0,
        "channel": "email",
        "recovered": 12000.00,
        "retries": 1,
        "minutes_ago": 120,
        "customer_intent": "DISCOUNT_ACCEPTED",
        "root_cause_discovery": "Bank gateway temporary timeout; recovered with zero margin erosion via automated fallback link",
        "promise_to_pay_date": None,
        "ptp_status": None,
        "voice_transcript": None,
    },
    {
        "name": "Neha Kapur",
        "email": "neha.kapur@lifestyledecor.in",
        "phone": "+919810998877",
        "total_spent": 16400.0,
        "txns": 4,
        "failed_txns": 1,
        "amount": 4299.0,
        "code": "USER_DROPOUT",
        "reason": "Abandoned cart on shipping confirmation step",
        "category": FailureCategory.USER_DROPOUT,
        "loss_vector": LossVector.CHECKOUT_DROPOFF,
        "status": TransactionStatus.PROCESSING,
        "escalation_level": 1,
        "discount": 10.0,
        "channel": "whatsapp",
        "recovered": 0.0,
        "retries": 1,
        "minutes_ago": 18,
        "customer_intent": "DISCOUNT_ACCEPTED",
        "root_cause_discovery": "Customer hesitated on delivery timeline; 10% coupon applied with cart held for 24 hours",
        "promise_to_pay_date": None,
        "ptp_status": None,
        "voice_transcript": None,
    },
    {
        "name": "Rajesh Sundaram",
        "email": "rajesh.s@speedcargo.co.in",
        "phone": "+919444123890",
        "total_spent": 64000.0,
        "txns": 7,
        "failed_txns": 1,
        "amount": 15750.0,
        "code": "INSUFFICIENT_FUNDS",
        "reason": "Current account debit limit reached due to bulk supplier RTGS batch",
        "category": FailureCategory.INSUFFICIENT_FUNDS,
        "loss_vector": LossVector.VOICE_RECOVERY,
        "status": TransactionStatus.PROCESSING,
        "escalation_level": 4,
        "discount": 5.0,
        "channel": "voice_ivr",
        "recovered": 0.0,
        "retries": 1,
        "minutes_ago": 40,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "Customer confirmed account replenishment scheduled tomorrow 2 PM post client remittance credit",
        "promise_to_pay_date": "Tomorrow 3:00 PM",
        "ptp_status": "PENDING",
        "voice_transcript": {
            "call_id": "call_rsund_9444",
            "customer_name": "Rajesh Sundaram",
            "customer_phone": "+919444123890",
            "customer_email": "rajesh.s@speedcargo.co.in",
            "order_amount": 15750.0,
            "discount_offered": 5.0,
            "customer_intent": "PROMISE_TO_PAY",
            "root_cause_discovery": "Customer confirmed account replenishment scheduled tomorrow 2 PM post client remittance credit",
            "promise_to_pay_date": "Tomorrow 3:00 PM",
            "call_outcome": "PROMISED",
            "call_duration_seconds": 78,
            "sms_payment_link_triggered": True,
            "failure_reason": "Current account debit limit reached due to bulk supplier RTGS batch",
            "dialogue": [
                {"speaker": "agent", "text": "Vanakkam Rajesh sir! Priya from SpeedCargo Software billing. Your SaaS renewal encountered a debit limit block."},
                {"speaker": "customer", "text": "Yes Priya, aaj vendor payments release hue the so daily limit finish ho gayi. Client ka cheque kal 2 PM clear hoga."},
                {"speaker": "agent", "text": "Understood sir! Humne service disruption hold pe daal diya hai. Tomorrow 3 PM payment complete karna theek rahega?"},
                {"speaker": "customer", "text": "Haan bilkul, kal 3 baje tak funds available rahenge, main complete kar dunga."},
                {"speaker": "agent", "text": "Nandri sir! Payment link SMS and WhatsApp pe bheja gaya hai. Have a good day!"}
            ]
        },
    },
    {
        "name": "Ananya Sen",
        "email": "ananya.sen@designstudio.org",
        "phone": "+919933445566",
        "total_spent": 7200.0,
        "txns": 2,
        "failed_txns": 1,
        "amount": 2499.0,
        "code": "NETWORK_TIMEOUT",
        "reason": "Client-side TCP socket hangup during payment processing",
        "category": FailureCategory.NETWORK_TIMEOUT,
        "loss_vector": LossVector.CHECKOUT_DROPOFF,
        "status": TransactionStatus.RECOVERED,
        "escalation_level": 1,
        "discount": 5.0,
        "channel": "whatsapp",
        "recovered": 2374.05,
        "retries": 1,
        "minutes_ago": 85,
        "customer_intent": "DISCOUNT_ACCEPTED",
        "root_cause_discovery": "Transient home WiFi disconnect; paid immediately when WhatsApp recovery link was clicked via mobile 5G",
        "promise_to_pay_date": None,
        "ptp_status": None,
        "voice_transcript": None,
    },
    {
        "name": "Vikram Malhotra",
        "email": "vikram.m@corporatesys.com",
        "phone": "+919845012345",
        "total_spent": 0.0,
        "txns": 0,
        "failed_txns": 3,
        "amount": 29999.0,
        "code": "CARD_EXPIRED",
        "reason": "Corporate credit card expired 08/26; recurring auto-debit rejected by bank",
        "category": FailureCategory.EXPIRED_CARD,
        "loss_vector": LossVector.FAILED_SUBSCRIPTION,
        "status": TransactionStatus.ABANDONED,
        "escalation_level": 2,
        "discount": 0.0,
        "channel": "email",
        "recovered": 0.0,
        "retries": 2,
        "minutes_ago": 320,
        "customer_intent": "TECHNICAL_OBJECTION",
        "root_cause_discovery": "Procurement transitioning ERP vendors; renewal declined intentionally by customer treasury department",
        "promise_to_pay_date": None,
        "ptp_status": None,
        "voice_transcript": None,
    },
    {
        "name": "Meera Nambiar",
        "email": "meera.nambiar@ayurwellness.in",
        "phone": "+919744889900",
        "total_spent": 9600.0,
        "txns": 3,
        "failed_txns": 1,
        "amount": 3199.0,
        "code": "INSUFFICIENT_FUNDS",
        "reason": "UPI AutoPay mandate failed due to low balance on primary VPA",
        "category": FailureCategory.INSUFFICIENT_FUNDS,
        "loss_vector": LossVector.MANDATE_DEGRADATION,
        "status": TransactionStatus.PROCESSING,
        "escalation_level": 2,
        "discount": 5.0,
        "channel": "whatsapp",
        "recovered": 0.0,
        "retries": 1,
        "minutes_ago": 28,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "Customer requested recurring mandate retry to align with pension disbursement on 3rd of month",
        "promise_to_pay_date": "Payday: 3rd of Month",
        "ptp_status": "PENDING",
        "voice_transcript": None,
    },
    {
        "name": "Sameer Kulkarni",
        "email": "sameer.k@medpulse.in",
        "phone": "+919823098765",
        "total_spent": 42000.0,
        "txns": 5,
        "failed_txns": 1,
        "amount": 21000.0,
        "code": "PAYMENT_DECLINED",
        "reason": "Daily POS/E-commerce limit exceeded on IndusInd Business Card",
        "category": FailureCategory.PAYMENT_DECLINED,
        "loss_vector": LossVector.VOICE_RECOVERY,
        "status": TransactionStatus.PROCESSING,
        "escalation_level": 3,
        "discount": 5.0,
        "channel": "voice_ivr",
        "recovered": 0.0,
        "retries": 1,
        "minutes_ago": 48,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "Doctor on surgery schedule; agreed to authorize transaction tomorrow morning from clinic desktop",
        "promise_to_pay_date": "Tomorrow 10:00 AM",
        "ptp_status": "PENDING",
        "voice_transcript": {
            "call_id": "call_skulk_9823",
            "customer_name": "Dr. Sameer Kulkarni",
            "customer_phone": "+919823098765",
            "customer_email": "sameer.k@medpulse.in",
            "order_amount": 21000.0,
            "discount_offered": 5.0,
            "customer_intent": "PROMISE_TO_PAY",
            "root_cause_discovery": "Doctor on surgery schedule; agreed to authorize transaction tomorrow morning from clinic desktop",
            "promise_to_pay_date": "Tomorrow 10:00 AM",
            "call_outcome": "PROMISED",
            "call_duration_seconds": 60,
            "sms_payment_link_triggered": True,
            "failure_reason": "Daily POS/E-commerce limit exceeded on IndusInd Business Card",
            "dialogue": [
                {"speaker": "agent", "text": "Namaste Dr. Kulkarni, Priya from MedPulse Telehealth. Your telemedicine annual subscription transaction failed."},
                {"speaker": "customer", "text": "Hello Priya, main abhi surgery OT mein hoon, IndusInd card ka limit block ho gaya tha."},
                {"speaker": "agent", "text": "Dr. Kulkarni, please carry on with patient care! Humne aapka portal access keep-alive rakha hai. Kal subah comfortable rahega?"},
                {"speaker": "customer", "text": "Yes, tomorrow morning 10 AM clinic desktop se main netbanking se transfer kar dunga."},
                {"speaker": "agent", "text": "Wonderful Doctor! 10 AM locked. Sending payment link on WhatsApp. Take care!"}
            ]
        },
    },
    {
        "name": "Divya Balan",
        "email": "divya.balan@eduskill.org",
        "phone": "+919895012345",
        "total_spent": 18000.0,
        "txns": 2,
        "failed_txns": 1,
        "amount": 14999.0,
        "code": "INSUFFICIENT_FUNDS",
        "reason": "Student loan installment disbursement delayed by partner NBFC",
        "category": FailureCategory.INSUFFICIENT_FUNDS,
        "loss_vector": LossVector.VOICE_RECOVERY,
        "status": TransactionStatus.PROCESSING,
        "escalation_level": 5,
        "discount": 10.0,
        "channel": "voice_ivr",
        "recovered": 0.0,
        "retries": 1,
        "minutes_ago": 65,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "NBFC student loan tranche releasing on Friday; confirmed course seat reservation hold until then",
        "promise_to_pay_date": "Friday 4:00 PM",
        "ptp_status": "PENDING",
        "voice_transcript": {
            "call_id": "call_dbala_9895",
            "customer_name": "Divya Balan",
            "customer_phone": "+919895012345",
            "customer_email": "divya.balan@eduskill.org",
            "order_amount": 14999.0,
            "discount_offered": 10.0,
            "customer_intent": "PROMISE_TO_PAY",
            "root_cause_discovery": "NBFC student loan tranche releasing on Friday; confirmed course seat reservation hold until then",
            "promise_to_pay_date": "Friday 4:00 PM",
            "call_outcome": "PROMISED",
            "call_duration_seconds": 92,
            "sms_payment_link_triggered": True,
            "failure_reason": "Student loan installment disbursement delayed by partner NBFC",
            "dialogue": [
                {"speaker": "agent", "text": "Namaste Divya ji! Priya here from EduSkill Career Accelerator. Noticed the Full Stack Cohort payment didn't go through."},
                {"speaker": "customer", "text": "Haan Priya ma'am, actually mera education loan sanction ho chuka hai but disbursement Friday afternoon tak aayega."},
                {"speaker": "agent", "text": "Don't worry at all Divya! We are holding your cohort seat and have applied a special 10% scholarship concession."},
                {"speaker": "customer", "text": "Thank you so much! Friday 4 PM jaise hi account mein amount credit hoga main direct link se pay kar dungi."},
                {"speaker": "agent", "text": "Pakka Divya! Friday 4 PM note kar liya hai. All the very best for your preparation!"}
            ]
        },
    },
    {
        "name": "Harish Bansal",
        "email": "harish.bansal@bansaltools.in",
        "phone": "+919818812345",
        "total_spent": 29000.0,
        "txns": 4,
        "failed_txns": 1,
        "amount": 9750.0,
        "code": "BAD_REQUEST_ERROR",
        "reason": "UPI app crashed during biometric fingerprint authentication prompt",
        "category": FailureCategory.USER_DROPOUT,
        "loss_vector": LossVector.CHECKOUT_DROPOFF,
        "status": TransactionStatus.RECOVERED,
        "escalation_level": 1,
        "discount": 5.0,
        "channel": "whatsapp",
        "recovered": 9262.50,
        "retries": 1,
        "minutes_ago": 110,
        "customer_intent": "DISCOUNT_ACCEPTED",
        "root_cause_discovery": "PhonePe application crashed on biometric step; resumed and recovered seamlessly via WhatsApp recovery link",
        "promise_to_pay_date": None,
        "ptp_status": None,
        "voice_transcript": None,
    },
    {
        "name": "Aarav Patel",
        "email": "aarav.p@datadrive.co",
        "phone": "+919879012345",
        "total_spent": 12000.0,
        "txns": 1,
        "failed_txns": 2,
        "amount": 32000.0,
        "code": "INSUFFICIENT_FUNDS",
        "reason": "Quarterly corporate marketing budget allocation delayed pending board sign-off",
        "category": FailureCategory.INSUFFICIENT_FUNDS,
        "loss_vector": LossVector.VOICE_RECOVERY,
        "status": TransactionStatus.FAILED,
        "escalation_level": 5,
        "discount": 10.0,
        "channel": "voice_ivr",
        "recovered": 0.0,
        "retries": 2,
        "minutes_ago": 300,
        "customer_intent": "PROMISE_TO_PAY",
        "root_cause_discovery": "CFO withheld Q3 marketing budget approval; customer was unable to honor the promised payment deadline",
        "promise_to_pay_date": "Breached: 3 days ago",
        "ptp_status": "BREACHED",
        "voice_transcript": {
            "call_id": "call_apat_9879",
            "customer_name": "Aarav Patel",
            "customer_phone": "+919879012345",
            "customer_email": "aarav.p@datadrive.co",
            "order_amount": 32000.0,
            "discount_offered": 10.0,
            "customer_intent": "PROMISE_TO_PAY",
            "root_cause_discovery": "CFO withheld Q3 marketing budget approval; customer was unable to honor the promised payment deadline",
            "promise_to_pay_date": "Breached: 3 days ago",
            "call_outcome": "BREACHED",
            "call_duration_seconds": 84,
            "sms_payment_link_triggered": True,
            "failure_reason": "Quarterly corporate marketing budget allocation delayed pending board sign-off",
            "dialogue": [
                {"speaker": "agent", "text": "Hello Aarav ji, Priya from DataDrive Enterprise suite. Checking in regarding your team subscription."},
                {"speaker": "customer", "text": "Priya, we promised to pay by Tuesday but management put marketing spend on hold for Q3 audit."},
                {"speaker": "agent", "text": "I see Aarav ji. Should we schedule a callback next quarter or freeze the instance?"},
                {"speaker": "customer", "text": "Please freeze for now, we won't be able to clear this invoice this week."},
                {"speaker": "agent", "text": "Understood Aarav ji. We will update the account status accordingly. Thank you."}
            ]
        },
    },
]


async def seed_database():
    await init_db()
    print("[*] Seeding database with rich, realistic Indian payment transactions and PTP commitments...", flush=True)

    async with async_session_maker() as session:
        # Clear existing records to ensure fresh, clean data state
        await session.execute(delete(AuditLog))
        await session.execute(delete(Transaction))
        await session.execute(delete(Customer))
        await session.commit()

        for data in SEED_CUSTOMERS:
            # Create Customer
            cust = Customer(
                name=data["name"],
                email=data["email"],
                phone=data["phone"],
                risk_score=0.10 if data["status"] == TransactionStatus.RECOVERED else (0.75 if data.get("ptp_status") == "BREACHED" else 0.35),
                total_spent=data["total_spent"] + data["recovered"],
                successful_transactions_count=data["txns"] + (1 if data["status"] == TransactionStatus.RECOVERED else 0),
                failed_transactions_count=data["failed_txns"],
            )
            session.add(cust)
            await session.commit()
            await session.refresh(cust)

            order_id = f"order_{uuid.uuid4().hex[:10]}"
            payment_id = f"pay_{uuid.uuid4().hex[:10]}"
            link_id = f"plink_{uuid.uuid4().hex[:8]}"
            recovery_link = f"https://rzp.io/i/{link_id}"

            created_time = datetime.utcnow() - timedelta(minutes=data["minutes_ago"])

            transcript_str = json.dumps(data["voice_transcript"]) if data.get("voice_transcript") else None

            # Create Transaction
            txn = Transaction(
                razorpay_order_id=order_id,
                razorpay_payment_id=payment_id,
                customer_id=cust.id,
                amount=data["amount"],
                currency="INR",
                status=data["status"],
                loss_vector=data.get("loss_vector", LossVector.CHECKOUT_DROPOFF),
                escalation_level=data.get("escalation_level", 1),
                failure_code=data["code"],
                failure_reason=data["reason"],
                failure_category=data["category"],
                retry_count=data["retries"],
                max_retries=2,
                recovery_link=recovery_link,
                recovery_channel=data["channel"],
                discount_applied_percent=data["discount"],
                recovered_amount=data["recovered"],
                promise_to_pay_date=data.get("promise_to_pay_date"),
                ptp_status=data.get("ptp_status"),
                voice_call_transcript=transcript_str,
                ptp_reminder_sent=bool(data.get("ptp_status") in ["FULFILLED", "BREACHED"]),
                dispatch_scheduled_at=created_time + timedelta(hours=4) if data.get("promise_to_pay_date") else None,
                auto_retry_enabled=data["status"] != TransactionStatus.ABANDONED,
                created_at=created_time,
                updated_at=datetime.utcnow() - timedelta(minutes=max(1, data["minutes_ago"] - 2)),
            )
            session.add(txn)
            await session.commit()
            await session.refresh(txn)

            # Create Diagnostic Audit Log
            diag_log = AuditLog(
                transaction_id=txn.id,
                customer_id=cust.id,
                agent_name="DiagnosticAgent",
                action_type=ActionType.DIAGNOSIS_COMPLETED,
                status=AuditStatus.SUCCESS,
                input_payload=json.dumps({
                    "order_id": order_id,
                    "amount": data["amount"],
                    "failure_code": data["code"],
                    "reason": data["reason"],
                }),
                output_payload=json.dumps({
                    "category": data["category"].value,
                    "can_retry": data["status"] != TransactionStatus.ABANDONED,
                    "risk_score": cust.risk_score,
                    "discovery": data.get("root_cause_discovery"),
                    "recommendation": f"Initiate recovery via {data['channel']} with {data['discount']}% discount.",
                }),
                execution_duration_ms=round(random.uniform(32.0, 75.0), 2),
                created_at=created_time + timedelta(seconds=2),
            )
            session.add(diag_log)

            # Create Strategy Audit Log
            strat_log = AuditLog(
                transaction_id=txn.id,
                customer_id=cust.id,
                agent_name="StrategyAgent",
                action_type=ActionType.STRATEGY_DECIDED,
                status=AuditStatus.SUCCESS,
                input_payload=json.dumps({
                    "diagnosis_category": data["category"].value,
                    "customer_intent": data.get("customer_intent", "PROMISE_TO_PAY"),
                }),
                output_payload=json.dumps({
                    "channel": data["channel"],
                    "discount_percent": data["discount"],
                    "offer_code": f"SAVE{int(data['discount'])}" if data["discount"] > 0 else None,
                    "tone": "empathic_hinglish" if data["channel"] == "voice_ivr" else ("casual_hinglish" if data["channel"] == "whatsapp" else "professional"),
                }),
                execution_duration_ms=round(random.uniform(40.0, 85.0), 2),
                created_at=created_time + timedelta(seconds=4),
            )
            session.add(strat_log)

            # Create Payment Link Tool Audit Log
            link_log = AuditLog(
                transaction_id=txn.id,
                customer_id=cust.id,
                agent_name="RazorpayPaymentLinkTool",
                action_type=ActionType.PAYMENT_LINK_GENERATED,
                status=AuditStatus.SUCCESS,
                input_payload=json.dumps({"amount": data["amount"], "discount": data["discount"]}),
                output_payload=json.dumps({"short_url": recovery_link, "link_id": link_id}),
                execution_duration_ms=round(random.uniform(15.0, 35.0), 2),
                created_at=created_time + timedelta(seconds=6),
            )
            session.add(link_log)

            # Create Outreach / Voice Dispatch Audit Log
            first_name = data["name"].split()[0]
            if data["channel"] == "voice_ivr":
                voice_log = AuditLog(
                    transaction_id=txn.id,
                    customer_id=cust.id,
                    agent_name="HinglishVoiceAgent",
                    action_type=ActionType.VOICE_CALL_DISPATCHED,
                    status=AuditStatus.SUCCESS,
                    input_payload=json.dumps({
                        "recipient": data["phone"],
                        "intent_target": data.get("customer_intent", "PROMISE_TO_PAY"),
                        "amount": data["amount"],
                    }),
                    output_payload=json.dumps({
                        "call_outcome": data.get("voice_transcript", {}).get("call_outcome", "PROMISED"),
                        "customer_intent": data.get("customer_intent", "PROMISE_TO_PAY"),
                        "promise_to_pay_date": data.get("promise_to_pay_date"),
                        "duration_seconds": data.get("voice_transcript", {}).get("call_duration_seconds", 75),
                    }),
                    execution_duration_ms=round(random.uniform(110.0, 180.0), 2),
                    created_at=created_time + timedelta(seconds=8),
                )
                session.add(voice_log)
            elif data["channel"] == "whatsapp":
                msg_text = (
                    f"Hey {first_name}! Aapka payment complete nahi hua. "
                    f"Special {int(data['discount'])}% discount apply kar diya hai. "
                    f"Click below to complete checkout securely!"
                )
                wa_log = AuditLog(
                    transaction_id=txn.id,
                    customer_id=cust.id,
                    agent_name="WhatsAppDispatchTool",
                    action_type=ActionType.WHATSAPP_DISPATCHED,
                    status=AuditStatus.SUCCESS,
                    input_payload=json.dumps({"recipient": data["phone"], "message": msg_text}),
                    output_payload=json.dumps({"status": "delivered", "read": True}),
                    execution_duration_ms=round(random.uniform(10.0, 25.0), 2),
                    created_at=created_time + timedelta(seconds=8),
                )
                session.add(wa_log)
            else:
                em_log = AuditLog(
                    transaction_id=txn.id,
                    customer_id=cust.id,
                    agent_name="SMTPDispatchTool",
                    action_type=ActionType.EMAIL_DISPATCHED,
                    status=AuditStatus.SUCCESS,
                    input_payload=json.dumps({"recipient": data["email"]}),
                    output_payload=json.dumps({"delivered": True, "mode": "smtp_gateway"}),
                    execution_duration_ms=round(random.uniform(60.0, 120.0), 2),
                    created_at=created_time + timedelta(seconds=8),
                )
                session.add(em_log)

            if data["status"] == TransactionStatus.RECOVERED:
                rec_log = AuditLog(
                    transaction_id=txn.id,
                    customer_id=cust.id,
                    agent_name="WebhookVerifier",
                    action_type=ActionType.RECOVERY_VERIFIED,
                    status=AuditStatus.SUCCESS,
                    input_payload=json.dumps({"payment_link": recovery_link, "amount": data["recovered"]}),
                    output_payload=f"Revenue recovered successfully: INR {data['recovered']:.2f}",
                    created_at=created_time + timedelta(minutes=random.randint(2, 10)),
                )
                session.add(rec_log)

            await session.commit()

        print(f"[PASS] Successfully seeded {len(SEED_CUSTOMERS)} comprehensive Indian recovery records & PTP commitments!", flush=True)


if __name__ == "__main__":
    asyncio.run(seed_database())
